BEGIN;
CREATE TABLE IF NOT EXISTS v2_state (user_id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS v2_records (record_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,mode TEXT NOT NULL,created_at TEXT NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS v2_public_539 (target_date TEXT PRIMARY KEY,locked_at TEXT NOT NULL,digest TEXT NOT NULL,payload TEXT NOT NULL,actual TEXT,verified_at TEXT);
CREATE TABLE IF NOT EXISTS v2_events (event_id TEXT PRIMARY KEY,status TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS v2_bingo_provenance (period TEXT PRIMARY KEY,source TEXT NOT NULL,fetched_at TEXT NOT NULL);
COMMIT;
